
modLoader="javafml" #//mandatory
loaderVersion="*" # // mandatory. Allow all forge versions as we are definding what Minecraft versions we requre later on
license="LGPL"
issueTrackerURL="${issues}"


[[mods]] #//mandatory
	modId="lod" #//mandatory
	version= "${version}" #//mandatory, gets the version number from jar populated by the build.gradle script
	displayName="${mod_name}" #//mandatory
	authors=$authors
	#//updateJSONURL="https://change.me.example.invalid/updates.json" # A URL to query for updates for this mod. See the JSON update specification https://mcforge.readthedocs.io/en/latest/gettingstarted/autoupdate/
	displayURL="${homepage}"
	description= "${description}" #//mandatory. The description text for the mod
	logoFile="logo.png"
	catalogueImageIcon="icon.png"
	credits="Massive thanks to: Leonardo, Cola, Ran, CoolGi, and Leetom. For their hard work to bring Distant Horizons to where it is today. - James"
	#// if not set defaults to "false"
	clientSideOnly="true"
	#// if not set side defaults to "BOTH"
	#// TODO change to "BOTH" when we add server support
	side="CLIENT"
	#// Allow any version to be present (or not) on the server
	acceptableRemoteVersions="*"


[[dependencies.lod]]
	modId="minecraft"
	mandatory=true
	versionRange="${compatible_forgemc_versions}" # Where we set what version of mc it is avalible for
	ordering="NONE"
	side="BOTH"